
	var aMenu = new Array(5);
	
	var MenuItem = '<li class="top" xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/overview.html?">Overview</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/DigitalCable/digitalcable.html?">XFINITY TV </a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/HighSpeedInternet/highspeedinternet.html">XFINITY Internet </a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/DigitalVoice/digitalvoice.html?">XFINITY Voice </a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/Bundles/doubleplay.html?">XFINITY Double Play</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/Bundles/bundles.html?">XFINITY Triple Play </a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/xfinity/wireless-mobile-broadband.html?">XFINITY Internet 2go</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;/homesecurity&quot;,&quot;&quot;,&quot;width=1175,height=950,menubar=no,toolbar=no,scrollbars=yes,resizable=yes,location=yes,status=no&quot;).focus()" href="#">XFINITY Home Security</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;https://signaturesupport.xfinity.com/?utm_source=comcastcom&amp;utm_medium=pulldown&amp;utm_campaign=consistentpulldownproduct&amp;CMP=cpd-comcast-20111116-comcastcom-001&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">XFINITY Signature Support</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Learn/Compare/index.html?">Compare the Competition</a></li>' + '<li class="bottom" xmlns:df="urn:dfExtensions"><a href="http://business.comcast.com/?INTCMP=ILC-DOTCOM-20100621-LRNBIZ-001">Comcast Business Services</a></li>'
	aMenu[0] = MenuItem;
  
	var MenuItem = '<li class="top" xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/shop/buyflow2/products.cspx?SourcePage=Cable">XFINITY TV</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/shop/buyflow2/products.cspx?SourcePage=Internet">XFINITY Internet </a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/shop/buyflow2/products.cspx?SourcePage=Voip">XFINITY Voice</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/shop/buyflow2/products.cspx?SourcePage=cableinternet">XFINITY Double Play</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/shop/buyflow2/products.cspx?SourcePage=Bundled">XFINITY Triple Play</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/shop/buyflow2/products.cspx?TargetId=34310a56-27e6-4316-bb35-bfe6e4a946e5">XFINITY Internet 2go</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;https://signaturesupport.xfinity.com/?utm_source=comcastcom&amp;utm_medium=pulldown&amp;utm_campaign=consistentpulldownshop&amp;CMP=cpd-comcast-20111116-comcastcom-002&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">XFINITY Signature Support</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Shop/ProductOverview.html">See All Products </a></li>' + '<li class="bottom" xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Shop/Retail/RetailStorelocator.html">Retail Locations</a></li>'
	aMenu[1] = MenuItem;
  
	var MenuItem = '<li class="top" xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://www.comcast.net/tv/on-demand/&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">On Demand Highlights </a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://www.mostlivesports.com&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Sports</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Programming/Comingevents.ashx">Pay-Per-View Events</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Customers/Clu/ChannelLineup.ashx">Channel Lineup</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://xfinitytv.comcast.net/&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">What\'s On</a></li>' + '<li class="bottom" xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Programming/IntlNetworks/default.html">International Programming</a></li>'
	aMenu[2] = MenuItem;
  
	var MenuItem = '<li class="top" xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Movers/Move.cspx">Move or Transfer Service</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;https://customer.comcast.com/Secure/Home.aspx&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Manage My Account </a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://xfinity.comcast.net/constantguard/&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Security</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/shop/retail/StoreLocator.html">Service Center Locations</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Customers/contactus/ContactUs.html?">Contact Us</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Customers/ParentalControls.html">Parental Controls</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://xfinity.comcast.net&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">xfinity.comcast.net</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Customers/Policies/Policies.html">Customer Agreements/Policies</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Customers/custcare.html">Customer Care</a></li>' + '<li class="bottom" xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Customers/CustomerGuarantee2.html">Customer Guarantee</a></li>'
	aMenu[3] = MenuItem;
  
	var MenuItem = '<li class="top" xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://customer.comcast.com/Pages/Help.aspx&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Help Overview</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://customer.comcast.com/Pages/HelpFolders.aspx?topic=Billing&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Account &amp; Billing</a></li>' + '<li xmlns:df="urn:dfExtensions"><a href="http://www.comcast.com/Corporate/Customers/Membership/Bill/BillExplanation.html">Understanding Your Bill</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://customer.comcast.com/Pages/HelpFolders.aspx?topic=Internet&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Internet</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://customer.comcast.com/Pages/HelpFolders.aspx?topic=Cable&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Cable TV</a></li>' + '<li xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://customer.comcast.com/Pages/HelpFolders.aspx?topic=Voice&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Voice</a></li>' + '<li class="bottom" xmlns:df="urn:dfExtensions"><a onclick="window.open(&quot;http://customer.comcast.com/Pages/HelpFolders.aspx?topic=Internet2Go&quot;,&quot;&quot;,&quot;&quot;).focus()" href="#">Internet 2go</a></li>'
	aMenu[4] = MenuItem;
  