// JavaScript Document
//note that these items should be copied to /Common/about_us/flash/network/TickerItems.xml but no longer used in Teamsite - Send to Requestor	


function networkNewsTicker() {
		
document.write('<ul>'
						+ '<li class="first"><h6>Recent Network Enhancements:</h6></li>'
						+ '<li><a href="http://focus.att.com/atl/" title="Atlanta" target="_blank">Atlanta</a></li>'
						+ '<li><a href="http://focus.att.com/dfw/" title="Dallas-Fort Worth" target="_blank">Dallas-Fort Worth</a></li>'
						+ '<li><a href="http://focus.att.com/detroit/" title="Detroit" target="_blank">Detroit</a></li>'
						+ '<li><a href="http://focus.att.com/houston/" title="Houston" target="_blank">Houston</a></li>'
						+ '<li><a href="http://focus.att.com/indy/" title="Indianapolis" target="_blank">Indianapolis</a></li>'
						+ '<li><a href="http://focus.att.com/kc/" title="Kansas City" target="_blank">Kansas City</a></li>'
						+ '<li><a href="http://focus.att.com/miami/" title="Miami" target="_blank">Miami</a></li>'
						+ '<li><a href="http://focus.att.com/philly/" title="Philadelphia" target="_blank">Philadelphia</a></li>'
						+ '<li><a href="http://focus.att.com/phx" title="Phoenix" target="_blank">Phoenix</a></li>'
						+ '<li><a href="http://focus.att.com/stl/" title="St. Louis" target="_blank">St. Louis</a></li>'
						+ '<li class="last"><a href="http://focus.att.com/tampa/" title="Tampa" target="_blank">Tampa</a></li>'
						+ '</ul>'
						+ '<div id="scrollup">'
						+ '<div class="headline">Nov. 22 - Announced two new cell sites in Orange County, NY</div>'
						+ '<div class="headline">Nov. 22 - Announced mobile broadband availability in the Smithfield area, VA</div>'
						+ '<div class="headline">Nov. 22 - Announced 10 new cell sites in Trumbull County, Brookfield, Cortland, Hartford and Kinsman, OH</div>'
						+ '<div class="headline">Nov. 22 - Announced 10 new cell sites in Tiffin, Attica, Fostoria and Republic, OH</div>'
						+ '<div class="headline">Nov. 22 - Announced 14 new cell sites in Marion, Caledonia and Waldo, OH</div>'
						+ '<div class="headline">Nov. 22 - Announced16 new cell sites in Lima and Bluffton and Harrod, OH</div>'
						+ '<div class="headline">Nov. 22 - Announced 25 new cell sites in Findlay and Bluffton, Carey, Fostoria, McComb, Rawson, and Upper Sandusky, OH</div>'
						+ '<div class="headline">Nov. 21 - Announced mobile broadband availability in Lexington and Buena Vista, VA</div>'
						+ '<div class="headline">Nov. 18 - Announced  mobile broadband availability in Franklinton, LA</div>'
						+ '<div class="headline">Nov. 17 - Announced three new cell sites in Belt, Raynesford and on Manchester Road near Sun Prairie, MT</div>'
						+ '<div class="headline">Nov. 17 - Announced completion of an initiative to enhance wireless capacity in Bergen, Essex and Union counties , NJ</div>'
						+ '<div class="headline">Nov. 17 - Announced two new cell sites in Three Forks on Interstate 90 and near Big Sky on Highway 191, MT</div>'
						+ '<div class="headline">Nov. 17 - Announced a new cell site in Kila, MT</div>'
						+ '<div class="headline">Nov. 17 - Announced new cell sites in Williamsburg, VA</div>'
						+ '<div class="headline">Nov. 16 - Announced mobile broadband network expansion in Bluefield, VA</div>'
						+ '<div class="headline">Nov. 16 - Announced upgrades to 73 cell sites in Hillsborough, Pinellas and Pasco counties, FL</div>'
						+ '<div class="headline">Nov. 16 - Announced completion of an initiative to enhance wireless capacity throughout Newport Beach, CA</div>'
						+ '<div class="headline">Nov. 15 - Announced that on Sunday, Nov. 20 Indianapolis will have access to the AT&T 4G LTE network, IN</div>'
						+ '<div class="headline">Nov. 15 - Announced a new mobile broadband site in Suffolk County, NY</div>'
						+ '<div class="headline">Nov. 15 - Announced two new cell sites downtown Houston and in the Galleria area, TX</div>'
						+ '<div class="headline">Nov. 15 - Announced a new cell site in Roanoke, VA</div>'
						+ '<div class="headline">Nov. 15 - Announced completion of an initiative to enhance wireless capacity throughout San Bernardino, CA</div>'
						+ '<div class="headline">Nov. 14 - Announced that on Sunday, Nov. 20 Oklahoma City will have access to the AT&T 4G LTE network, OK</div>'
						+ '<div class="headline">Nov. 14 - Announced that on Sunday, Nov. 20 Kansas City will have access to the AT&T 4G LTE network, MO</div>'
						+ '<div class="headline">Nov. 14 - Announced a new mobile site in White Settlement, TX</div>'
						+ '<div class="headline">Nov. 14 - Announced a new cell site in Fortuna Foothills, AZ</div>'
						+ '<div class="headline">Nov. 14 - Announced seven new cell sites in Rensselaer County, NY</div>'
						+ '<div class="headline">Nov. 14 - Announced that on Sunday, Nov. 20 Charlotte will have access to the AT&T 4G LTE network, NC</div>'
						+ '<div class="headline">Nov. 14 - Announced a new cell site in Amarillo, TX </div>'
						+ '<div class="headline">Nov. 11 - Announced mobile broadband coverage at the home of the Cincinnati Bengals, Paul Brown Stadium, OH</div>'
						 + '</div>'
						 + '<div class="clear"></div>');
}